### ISSUE TITLE
Criar publicação anunciando a campanha

### ISSUE THREAD

**Issue by barrosgg** [mozillabrasil/Privacy-Month-2017#8]
- [x] Texto da publicação
- [x] Imagem da publicação
- [x] Publicar no Facebook e Twitter
- [x] Publicar no blog da Mozilla Brasil

**Comment by barrosgg** [comment]
@cynthiapereira olha um pouco a ideia deste post, precisamos melhorar agora.
![mes_privacidade_chegando](https://cloud.githubusercontent.com/assets/14970832/21707523/b381fe16-d3ae-11e6-98e6-ebae83d54b98.jpg)

**Comment by cpswsg** [comment]
@barrosgeraldo Eu gostei do conceito, só precisa fazer os refinamentos.

**Comment by cpswsg** [comment]
### Sugestão de Texto

**Facebook**
> A cibersegurança é muito simples: envolve apenas proteger a si mesmo e suas informações on-line. Você não pode prevenir todas as ameaças – on-line ou na vida real. Mas você pode, definitivamente, minimizar seu risco com a consciência e bom senso de como as empresas e os governos acompanham e coletam seus dados. 

> Todo dia, até o final do mês de Janeiro, postaremos dicas e medidas de segurança recomendadas pela política de privacidade da Mozilla e de profissionais da área para que você saiba como proteger sua privacidade on-line. Não perca!

**Twitter**
> Veja, todo o dia até o final do mês, uma dica sobre como proteger sua privacidade on-line.

**Comment by maykonchagas** [comment]
já pode divulgar? imagem e texto incríveis! parabéns pessoal!

**Comment by barrosgg** [comment]
Maykon, só precisamos de melhorar a imagem, no caso o texto que há na imagem, tem sugestões? Ou acha que está bom assim?

**Comment by maykonchagas** [comment]
@barrosgeraldo @cynthiapereira Eu acho que poderíamos usar o Keep Calm, por mais que seja em inglês o brasileiro já conhece bem a expressão e sabe o significado. Talvez até poderíamos usar outra referência com outra imagem, "The winter is coming.." e faríamos "Mês da privacidade está chegando..". O que acham?

**Comment by mchagas** [comment]
talvez até poderíamos usar outra referência, "The winter is coming.." e faríamos "Mês da privacidade está chegando.."

**Comment by maykonchagas** [comment]
Junto da segunda proposta, "O Mês da Privacidade está chegando... " poderíamos usar algo como [essa imagem](https://images.duckduckgo.com/iu/?u=http%3A%2F%2Fcdn.eteknix.com%2Fwp-content%2Fuploads%2F2016%2F01%2Ffirefox-44.jpg&f=1) o que acham? deve ter essa imagem nos repos oficiais da Mozilla né? E aí adicionamos a hashtag #PrivacyMonth e o Mozilla Brasil

**Comment by barrosgg** [comment]
@mchagas, acho que podemos apenas manter essa imagem, o pessoal da India fez para ser tipo o cartaz da campanha, acredito que apenas o texto podemos melhorar.
Essa imagem que você mandou não pode ser utilizada, ela é do Firefox OS e não é aberta.

**Comment by barrosgg** [comment]
@mchagas o que acha de manter colocar apenas o "Keep Calm" no topo, substituindo o "mantenha a calma"?

**Comment by barrosgg** [comment]
![mes_privacidade_chegando](https://cloud.githubusercontent.com/assets/14970832/21729269/267733f8-d429-11e6-91aa-12b919c418bd.jpg)
Feita a alteração.

**Comment by barrosgg** [comment]
Agendada no Facebook da Mozilla Brasil

**Comment by barrosgg** [comment]
Publicado no Twitter

**Comment by barrosgg** [comment]
@cynthiapereira, eu estou impossibilitado de publicar qualquer coisa no blog da comunidade, eu estou tentando recuperar a senha, mas infelizmente não estou recebendo email de recuperação.

**Comment by cpswsg** [comment]
@barrosgeraldo Com a desativação do persona, os logins efetuados por meio dele pararam de funcionar. Gerei um acesso temporário para você. Por favor, siga os procedimentos enviados por pm.
