### ISSUE TITLE
Publicação 15/Jan

### ISSUE THREAD

**Issue by maykonchagas** [mozillabrasil/Privacy-Month-2017#9]
- [x] Resumo da 1a semana
- [x] Texto da publicação
- [x] Imagem da publicação
- [x] Agendar publicação no Twitter e Facebook

**Comment by barrosgg** [comment]
@mchagas, aqui talvez podemos fazer uma imagem com logos de todos os projetos envolvidos nas dicas que demos durante a semana ou apenas textos com o título de todas as dicas.
Mais ideias aqui?

**Comment by cpswsg** [comment]
Sugestão de texto

**Blog**
> Confira todas as dicas sobre privacidade on-line postadas durante essa semana: 
> 1. Navegação Privativa
> 2. Proteção contra rastreamento
> 3. Não me rastreie!
> 4. Botão Esquecer
> 5. Lightbeam
> 6. Firefox Focus

@barrosgeraldo e @mchagas, no Facebook e Twitter podemos colocar o link para a publicação do blog. O que acham?

**Comment by barrosgg** [comment]
Acho perfeito, vamos fazer isso.

**Comment by maykonchagas** [comment]
Também concordo @cynthiapereira, "Regina, let's go!" 😁

**Comment by barrosgg** [comment]
![template_facebook](https://cloud.githubusercontent.com/assets/14970832/21825739/b6811710-d763-11e6-84d4-8c450efe9c85.png)

**Comment by cpswsg** [comment]
@barrosgeraldo poderia alterar para: **Dicas da última semana:**

**Comment by maykonchagas** [comment]
Concordo com a @cynthiapereira

**Comment by barrosgg** [comment]
![dicas_semana_1](https://cloud.githubusercontent.com/assets/14970832/21825951/7ab3f17a-d764-11e6-860a-17a14ddc4a2f.png)

**Comment by barrosgg** [comment]
@cynthiapereira, no caso do blog post, você planeja fazer um post resumindo cada dia?

**Comment by cpswsg** [comment]
@barrosgeraldo Eu havia pensando em algo mais direto, mas é uma boa ideia ter pelo menos um parágrafo elucidativo. Vou trabalhar nisso!

**Comment by cpswsg** [comment]
**Blog**
> Confira todas as dicas sobre privacidade on-line postadas durante essa semana: 

> 1. Navegação Privativa
A navegação privativa do Firefox permite navegar na Internet sem salvar informações sobre os sites e páginas visitadas, dados em formulários, histórico de pesquisa e downloads, senhas, cookies e cache.

> 2. Proteção contra rastreamento
A proteção contra rastreamento na navegação privativa do Firefox diminui a capacidade de terceiros de rastrear suas atividades de navegação on-line em diferentes sites.

> 3. Não me rastreie!
O Não me rastreie informa aos sites que você visita, anunciantes e a outros provedores de conteúdo que não quer ser monitorado.

> 4. Botão Esquecer
O botão Esquecer limpa o histórico de navegação em um período de tempo selecionado, sem afetar o restante de suas configurações.

> 5. Lightbeam
O Lightbeam te mostra quantas empresas estão vigiando seu comportamento na Internet.

> 6. Firefox Focus
O Firefox Focus para iOS protege sua navegação contra rastreamento de forma fácil e rápida, sem precisar configurar nada. 

cc: @barrosgeraldo e @mchagas

**Comment by barrosgg** [comment]
Revisado.

**Comment by barrosgg** [comment]
@cynthiapereira, agendado no blog da comunidade. Nas redes sociais não é possível add o link para o blog.

**Comment by cpswsg** [comment]
@barrosgeraldo vamos precisar fazer a postagem nas redes sociais logo após a publicação no blog, ai teremos o link.  :wink:

**Comment by barrosgg** [comment]
@cynthiapereira , obrigado.
Postado, fechando.
